Repository verge-io/docs, pull requests merged in 2024-10, with the labels that each got.

#67 Content from training guides
  docs/glossary.md
  docs/product-guide/NAS-joinADDomain.md
  docs/product-guide/UI-Overview.md
  docs/product-guide/VM-workingwith.md
  docs/product-guide/network-dashboards.md
  docs/product-guide/screenshots/singletenantsubscription-report.png
  docs/product-guide/screenshots/tenantssubscription-alert.png
  docs/product-guide/screenshots/tenantssubscription-report.png
  docs/product-guide/subscriptions-overview.md
  docs/product-guide/tenant-modifications.md
  docs/product-guide/tenant-monitoring.md
  docs/product-guide/tenant-usagereports.md
  docs/product-guide/uploadingtovSAN.md
  docs/product-guide/usersgroups.md
  docs/product-guide/vm-manualmigration.md
  mkdocs.yml
Labels: documentation, Product Guide

#69 Fix missing cluster information
  docs/product-guide/system/clusters-config-options.md
  docs/product-guide/system/clusters.md
  mkdocs.yml
Labels: documentation, Product Guide

#76 update CI to build insiders
  .github/workflows/ci.yml
Labels: enhancement

#77 add breadcrumbs
  mkdocs.yml
Labels: documentation, enhancement

#78 Update pre-installation.md
  docs/implementation-guide/pre-installation.md
Labels: documentation

#79 post install guide
  docs/implementation-guide/post-installation.md
Labels: documentation

#80 Homelab Docs
  docs/knowledge-base/posts/create-external-network.md
  docs/public/knowledgebase/default-gateway-rule.png
  docs/public/knowledgebase/external-network-settings.png
  docs/reference-architecture/homelab.md
  mkdocs.yml
Labels: documentation, KB

#81 Fix broken links
  docs/implementation-guide/network-design.md
  docs/product-guide/createvlan.md
  docs/product-guide/importvmware.md
  mkdocs.yml
Labels: documentation
