Repository verge-io/docs, pull requests merged in 2024-11, with the labels that each got.

#82 4.13 - live migrations
  docs/product-guide/virtual-machines/live-migrations.md
  mkdocs.yml
Labels: documentation, Product Guide

#84 Storware KB article
  docs/knowledge-base/posts/storware-setup.md
Labels: documentation, KB

#85 added new branch and edit/view button
  mkdocs.yml
Labels: documentation, enhancement

#83 add vsan documents
  docs/assets/vsan_hash_map.png
  docs/knowledge-base/posts/adding-resources.md
  docs/knowledge-base/posts/scaling-up-a-vsan.md
  docs/product-guide/storagetiers.md
  docs/product-guide/virtual-machines/live-migrations.md
  docs/product-guide/vsan/architecture.md
  docs/product-guide/vsan/storage-tiers.md
  mkdocs.yml
Labels: documentation

#105 Fix typo
  docs/knowledge-base/posts/storware-setup.md
Labels: documentation

#110 Update post-installation.md
  docs/implementation-guide/post-installation.md
Labels: documentation
